name = "earth-special-force-online"
main = "src/index.ts"
compatibility_date = "2026-08-20"

[[durable_objects.bindings]]
name = "ROOM"
class_name = "GameRoom"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["GameRoom"]

[assets]
directory = "./public"

[[kv_namespaces]]
binding = "KV"
id = "0e9aa43710674bd19f4b1b0d2ec00776"